Repository DEEPDIVE-PROJECT-200/cherry-backend, pull requests merged in 2025-09, with the labels that each got.

#44 [FEATURE] 상품 엔티티 설계
  src/main/java/ok/cherry/product/domain/Product.java
  src/main/java/ok/cherry/product/domain/ProductDetail.java
  src/main/java/ok/cherry/product/domain/ProductImageDetail.java
  src/main/java/ok/cherry/product/domain/ProductThumbNailDetail.java
  src/main/java/ok/cherry/product/domain/type/Brand.java
  src/main/java/ok/cherry/product/domain/type/Color.java
  src/main/java/ok/cherry/product/exception/ProductError.java
Labels: ✨ feature

#46 [FEATURE] 장바구니 엔티티 설계
  src/main/java/ok/cherry/cart/domain/Cart.java
Labels: ✨ feature

#50 [FEATURE] 대여 엔티티 설계
  src/main/java/ok/cherry/rental/domain/Rental.java
  src/main/java/ok/cherry/rental/domain/RentalDetail.java
  src/main/java/ok/cherry/rental/domain/RentalItem.java
  src/main/java/ok/cherry/rental/domain/status/RentalStatus.java
  src/main/java/ok/cherry/rental/domain/status/ReviewStatus.java
Labels: ✨ feature

#51 [CHORE] S3 연동 설정
  build.gradle.kts
  src/main/java/ok/cherry/global/config/S3Config.java
  src/main/java/ok/cherry/global/s3/S3Service.java
  src/main/java/ok/cherry/global/s3/exception/S3Error.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/test/resources/application.yml
Labels: ⚙️ chore, ✨ feature

#56 [FEATURE] JWT 토큰 payload 정보 추가
  src/main/java/ok/cherry/auth/application/AuthService.java
  src/main/java/ok/cherry/auth/jwt/TokenGenerator.java
  src/main/java/ok/cherry/member/domain/Email.java
  src/main/java/ok/cherry/member/domain/Member.java
  src/main/java/ok/cherry/member/domain/MemberDetail.java
  src/test/java/ok/cherry/auth/jwt/TokenGeneratorTest.java
  src/test/java/ok/cherry/member/domain/MemberTest.java
Labels: ✨ feature

#63 [CI/CD] Spring Boot 애플리케이션 Dockerfile 및 K8s manifest 작성
  k8s/depl_svc.yml
  k8s/https.yml
  k8s/ingress.yml
  k8s/redis.yml
  src/main/java/ok/cherry/global/config/SecurityConfig.java
  src/main/java/ok/cherry/global/config/SwaggerConfig.java
  src/main/resources/application-prod.yml
Labels: 📦 ci/cd

#64 [CI/CD] GitHub Actions 기반 EKS 자동 배포 파이프라인 구성
  .github/workflows/deploy_cherry_on_main_with_k8s.yml
Labels: 📦 ci/cd

#67 [REFACTOR] 주문번호, 배송번호 생성 로직 분리
  src/main/java/ok/cherry/rental/domain/Rental.java
  src/main/java/ok/cherry/rental/exception/RentalError.java
  src/main/java/ok/cherry/rental/util/RentalNumberGenerator.java
  src/main/java/ok/cherry/shipping/domain/Shipping.java
  src/main/java/ok/cherry/shipping/exception/ShippingError.java
  src/main/java/ok/cherry/shipping/util/TrackingNumberGenerator.java
  src/test/java/ok/cherry/rental/RentalBuilder.java
  src/test/java/ok/cherry/rental/domain/RentalTest.java
  src/test/java/ok/cherry/shipping/ShippingBuilder.java
  src/test/java/ok/cherry/shipping/domain/ShippingTest.java
Labels: ♻️ refactor

#70 [CI/CD] Prod 환경 이미지 빌드 시 target 지정 추가
  .github/workflows/deploy_cherry_on_main_with_k8s.yml
Labels: 📦 ci/cd

#69 [FEATURE] 상품 등록 기능 구현
  src/main/java/ok/cherry/global/exception/GlobalExceptionHandler.java
  src/main/java/ok/cherry/global/swagger/product/ProductControllerDoc.java
  src/main/java/ok/cherry/product/application/ProductService.java
  src/main/java/ok/cherry/product/application/dto/request/ProductCreateRequest.java
  src/main/java/ok/cherry/product/application/dto/response/ProductCreateResponse.java
  src/main/java/ok/cherry/product/domain/Product.java
  src/main/java/ok/cherry/product/domain/ProductDetail.java
  src/main/java/ok/cherry/product/domain/ProductThumbnailDetail.java
  src/main/java/ok/cherry/product/domain/type/Brand.java
  src/main/java/ok/cherry/product/domain/type/Color.java
  src/main/java/ok/cherry/product/exception/ProductError.java
  src/main/java/ok/cherry/product/infrastructure/ProductRepository.java
  src/main/java/ok/cherry/product/presentation/ProductController.java
  src/test/java/ok/cherry/product/ProductBuilder.java
  src/test/java/ok/cherry/product/application/ProductServiceTest.java
  src/test/java/ok/cherry/product/domain/ProductTest.java
Labels: ✨ feature

#74 [FEATURE] S3 이미지 업로드 Controller
  src/main/java/ok/cherry/global/s3/S3Controller.java
  src/main/java/ok/cherry/global/s3/S3Service.java
  src/main/java/ok/cherry/global/s3/dto/request/FilesDeleteRequest.java
  src/main/java/ok/cherry/global/s3/dto/response/FilesDeleteResponse.java
  src/main/java/ok/cherry/global/s3/dto/response/ImageUploadResponse.java
  src/main/java/ok/cherry/global/s3/exception/S3Error.java
Labels: ✨ feature

#79 [CHORE] allowed-mime-types 환경변수 추가
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: ⚙️ chore

#82 [CHORE] 예외 로그 출력 기능 추가
  src/main/java/ok/cherry/global/exception/GlobalExceptionHandler.java
Labels: ⚙️ chore

#83 [Release] v0.0.3 - 예외 로그 출력 기능 추가
  src/main/java/ok/cherry/global/exception/GlobalExceptionHandler.java
Labels: 🚀 release

#87 [FEATURE] 장바구니 상품 추가, 삭제 기능 구현
  src/main/java/ok/cherry/cart/application/CartService.java
  src/main/java/ok/cherry/cart/application/dto/request/CartCreateRequest.java
  src/main/java/ok/cherry/cart/application/dto/request/CartDeleteRequest.java
  src/main/java/ok/cherry/cart/application/dto/response/CartCreateResponse.java
  src/main/java/ok/cherry/cart/exception/CartError.java
  src/main/java/ok/cherry/cart/infrastructure/CartRepository.java
  src/main/java/ok/cherry/cart/presentation/CartController.java
  src/main/java/ok/cherry/global/swagger/cart/CartControllerDoc.java
  src/test/java/ok/cherry/cart/application/CartServiceTest.java
Labels: ✨ feature

#92 [FEATURE] 결제 생성, 조회 기능 구현
  http/payment.http
  src/main/java/ok/cherry/global/swagger/payment/PaymentControllerDoc.java
  src/main/java/ok/cherry/payment/application/PaymentService.java
  src/main/java/ok/cherry/payment/application/dto/response/AdditionalFeeResponse.java
  src/main/java/ok/cherry/payment/application/dto/response/PaymentItemResponse.java
  src/main/java/ok/cherry/payment/application/dto/response/PaymentResponse.java
  src/main/java/ok/cherry/payment/domain/AdditionalFee.java
  src/main/java/ok/cherry/payment/domain/Payment.java
  src/main/java/ok/cherry/payment/domain/PaymentAmount.java
  src/main/java/ok/cherry/payment/domain/PaymentDetail.java
  src/main/java/ok/cherry/payment/domain/PaymentInfo.java
  src/main/java/ok/cherry/payment/domain/PaymentItem.java
  src/main/java/ok/cherry/payment/domain/RentalPeriod.java
  src/main/java/ok/cherry/payment/exception/PaymentError.java
  src/main/java/ok/cherry/payment/infrastructure/PaymentRepository.java
  src/main/java/ok/cherry/payment/presentation/PaymentController.java
  src/main/resources/application-local.yml
  src/main/resources/data.sql
  src/test/java/ok/cherry/payment/PaymentBuilder.java
  src/test/java/ok/cherry/payment/application/PaymentServiceTest.java
  src/test/java/ok/cherry/payment/domain/PaymentTest.java
  src/test/resources/application.yml
Labels: ✨ feature

#95 [FEATURE] 장바구니 상품 조회 기능 구현
  src/main/java/ok/cherry/cart/application/CartService.java
  src/main/java/ok/cherry/cart/application/dto/response/CartGetResponse.java
  src/main/java/ok/cherry/cart/application/dto/response/CartInfoResponse.java
  src/main/java/ok/cherry/cart/infrastructure/CartRepository.java
  src/main/java/ok/cherry/cart/presentation/CartController.java
  src/main/java/ok/cherry/global/swagger/cart/CartControllerDoc.java
  src/test/java/ok/cherry/cart/application/CartServiceTest.java
Labels: ✨ feature

#113 [FEATURE] 배송 생성 기능 구현
  src/main/java/ok/cherry/shipping/application/ShippingService.java
  src/main/java/ok/cherry/shipping/application/command/CreateShippingCommand.java
  src/main/java/ok/cherry/shipping/domain/Shipping.java
  src/main/java/ok/cherry/shipping/infrastructure/ShippingRepository.java
  src/main/java/ok/cherry/shipping/presentation/ShippingController.java
  src/test/java/ok/cherry/shipping/ShippingBuilder.java
  src/test/java/ok/cherry/shipping/domain/ShippingTest.java
Labels: ✨ feature

#114 [FEATURE] 체험 신청/결제 (대여 -> 결제 -> 배송)
  http/rental.http
  src/main/java/ok/cherry/cart/application/CartService.java
  src/main/java/ok/cherry/cart/application/dto/request/CartDeleteRequest.java
  src/main/java/ok/cherry/cart/application/dto/response/CartInfoResponse.java
  src/main/java/ok/cherry/cart/infrastructure/CartRepository.java
  src/main/java/ok/cherry/global/config/SwaggerConfig.java
  src/main/java/ok/cherry/global/swagger/rental/RentalControllerDoc.java
  src/main/java/ok/cherry/member/application/MemberService.java
  src/main/java/ok/cherry/payment/application/PaymentService.java
  src/main/java/ok/cherry/payment/application/dto/command/CreatePaymentCommand.java
  src/main/java/ok/cherry/product/application/ProductQueryService.java
  src/main/java/ok/cherry/rental/application/RentalApplicationService.java
  src/main/java/ok/cherry/rental/application/command/CreateRentalCommand.java
  src/main/java/ok/cherry/rental/application/request/AddressRequest.java
  src/main/java/ok/cherry/rental/application/request/OrderRequestShippingInfo.java
  src/main/java/ok/cherry/rental/application/request/PlaceRentalOrderRequest.java
  src/main/java/ok/cherry/rental/application/request/ShippingInfoRequest.java
  src/main/java/ok/cherry/rental/application/response/PlaceRentalOrderResponse.java
  src/main/java/ok/cherry/rental/exception/RentalError.java
  src/main/java/ok/cherry/rental/infrastructure/RentalRepository.java
  src/main/java/ok/cherry/rental/presentation/RentalController.java
  src/main/java/ok/cherry/shipping/application/command/CreateShippingCommand.java
  src/main/java/ok/cherry/shipping/domain/ShippingInfo.java
  src/main/java/ok/cherry/shipping/presentation/ShippingController.java
  src/main/resources/data.sql
  src/test/java/ok/cherry/cart/application/CartServiceTest.java
  src/test/java/ok/cherry/payment/application/PaymentServiceTest.java
  src/test/java/ok/cherry/rental/RentalBuilder.java
  src/test/java/ok/cherry/rental/application/RentalApplicationServiceTest.java
  src/test/java/ok/cherry/shipping/application/ShippingServiceTest.java
Labels: ✅ test, ✨ feature

#116 [FEATURE] Rental에 리뷰 상태 필드 추가
  src/main/java/ok/cherry/rental/application/response/RentalInfoResponse.java
  src/main/java/ok/cherry/rental/domain/Rental.java
  src/main/java/ok/cherry/rental/domain/RentalItem.java
  src/main/resources/data.sql
  src/test/java/ok/cherry/rental/domain/RentalItemTest.java
Labels: ✨ feature

#117 [FEATURE] 배송 시작, 완료 기능 구현
  src/main/java/ok/cherry/rental/domain/Rental.java
  src/main/java/ok/cherry/rental/exception/RentalError.java
  src/main/java/ok/cherry/shipping/application/ShippingService.java
  src/main/java/ok/cherry/shipping/domain/Shipping.java
  src/main/java/ok/cherry/shipping/domain/ShippingDetail.java
  src/main/java/ok/cherry/shipping/domain/type/Direction.java
  src/main/java/ok/cherry/shipping/exception/ShippingError.java
  src/test/java/ok/cherry/rental/domain/RentalTest.java
  src/test/java/ok/cherry/shipping/application/ShippingServiceTest.java
  src/test/java/ok/cherry/shipping/domain/ShippingTest.java
Labels: ✨ feature

#118 [FEATURE] 리뷰 작성 완료 기능 구현
  src/main/java/ok/cherry/rental/application/RentalService.java
  src/main/java/ok/cherry/rental/domain/Rental.java
  src/main/java/ok/cherry/rental/exception/RentalError.java
  src/test/java/ok/cherry/rental/application/RentalServiceTest.java
  src/test/java/ok/cherry/rental/domain/RentalTest.java
Labels: ✨ feature

#120 [DOCS] gemini 코드 컨벤션 문서 변경
  .gemini/styleguide.md
Labels: 📝 docs

#121 [FEATURE] 검수 완료 구현
  src/main/java/ok/cherry/rental/application/RentalApplicationService.java
  src/main/java/ok/cherry/rental/application/RentalService.java
  src/main/java/ok/cherry/rental/application/response/RentalCompleteResponse.java
  src/main/java/ok/cherry/shipping/application/ShippingService.java
  src/main/java/ok/cherry/shipping/exception/ShippingError.java
  src/main/java/ok/cherry/shipping/infrastructure/ShippingRepository.java
  src/test/java/ok/cherry/rental/application/RentalApplicationServiceTest.java
Labels: ✨ feature

#122 [FEATURE] 상품 상세 조회 기능 구현
  http/product.http
  src/main/java/ok/cherry/global/swagger/product/ProductControllerDoc.java
  src/main/java/ok/cherry/product/application/ProductQueryService.java
  src/main/java/ok/cherry/product/application/dto/response/ProductInfoResponse.java
  src/main/java/ok/cherry/product/presentation/ProductController.java
Labels: ✨ feature

#124 [FEATURE] 대여 상세 조회 기능 구현
  http/rental.http
  src/main/java/ok/cherry/global/swagger/auth/AuthControllerDoc.java
  src/main/java/ok/cherry/global/swagger/cart/CartControllerDoc.java
  src/main/java/ok/cherry/global/swagger/payment/PaymentControllerDoc.java
  src/main/java/ok/cherry/global/swagger/rental/RentalControllerDoc.java
  src/main/java/ok/cherry/rental/application/RentalService.java
  src/main/java/ok/cherry/rental/exception/RentalError.java
  src/main/java/ok/cherry/rental/infrastructure/RentalRepository.java
  src/main/java/ok/cherry/rental/presentation/RentalController.java
  src/test/java/ok/cherry/rental/application/RentalServiceTest.java
Labels: ✨ feature

#125 [FEATURE] 회원 탈퇴 기능 구현
  src/main/java/ok/cherry/member/application/MemberApplicationService.java
  src/main/java/ok/cherry/member/domain/Member.java
  src/main/java/ok/cherry/member/infrastructure/MemberRepository.java
  src/main/java/ok/cherry/member/presentation/MemberController.java
  src/test/java/ok/cherry/member/application/MemberApplicationServiceTest.java
Labels: ✨ feature

#132 [FEATURE] 사용자 총 환급 금액 및 총 대여 수 조회
  http/rental.http
  src/main/java/ok/cherry/global/swagger/rental/RentalControllerDoc.java
  src/main/java/ok/cherry/rental/application/RentalService.java
  src/main/java/ok/cherry/rental/application/response/RentalCountResponse.java
  src/main/java/ok/cherry/rental/infrastructure/RentalRepository.java
  src/main/java/ok/cherry/rental/presentation/RentalController.java
  src/test/java/ok/cherry/rental/application/RentalServiceTest.java
Labels: ✨ feature
